/* tslint:disable */
/* eslint-disable */
/**
 * Griot and Grits API
 * Griot and Grits API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AIContribution
 */
export interface AIContribution {
    /**
     * 
     * @type {string}
     * @memberof AIContribution
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AIContribution
     */
    aiTool?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AIContribution
     */
    originalContentPercentage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AIContribution
     */
    aiGeneratedPercentage?: number | null;
}

/**
 * Check if a given object implements the AIContribution interface.
 */
export function instanceOfAIContribution(value: object): value is AIContribution {
    return true;
}

export function AIContributionFromJSON(json: any): AIContribution {
    return AIContributionFromJSONTyped(json, false);
}

export function AIContributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIContribution {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'aiTool': json['ai_tool'] == null ? undefined : json['ai_tool'],
        'originalContentPercentage': json['original_content_percentage'] == null ? undefined : json['original_content_percentage'],
        'aiGeneratedPercentage': json['ai_generated_percentage'] == null ? undefined : json['ai_generated_percentage'],
    };
}

export function AIContributionToJSON(json: any): AIContribution {
    return AIContributionToJSONTyped(json, false);
}

export function AIContributionToJSONTyped(value?: AIContribution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'ai_tool': value['aiTool'],
        'original_content_percentage': value['originalContentPercentage'],
        'ai_generated_percentage': value['aiGeneratedPercentage'],
    };
}

