/* tslint:disable */
/* eslint-disable */
/**
 * Griot and Grits API
 * Griot and Grits API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Duration } from './Duration';
import {
    DurationFromJSON,
    DurationFromJSONTyped,
    DurationToJSON,
    DurationToJSONTyped,
} from './Duration';

/**
 * 
 * @export
 * @interface AudioMetadata
 */
export interface AudioMetadata {
    /**
     * 
     * @type {Duration}
     * @memberof AudioMetadata
     */
    duration?: Duration | null;
    /**
     * 
     * @type {number}
     * @memberof AudioMetadata
     */
    fileSizeMb?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AudioMetadata
     */
    codec?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AudioMetadata
     */
    channels?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AudioMetadata
     */
    sampleRate?: string | null;
}

/**
 * Check if a given object implements the AudioMetadata interface.
 */
export function instanceOfAudioMetadata(value: object): value is AudioMetadata {
    return true;
}

export function AudioMetadataFromJSON(json: any): AudioMetadata {
    return AudioMetadataFromJSONTyped(json, false);
}

export function AudioMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : DurationFromJSON(json['duration']),
        'fileSizeMb': json['file_size_mb'] == null ? undefined : json['file_size_mb'],
        'codec': json['codec'] == null ? undefined : json['codec'],
        'channels': json['channels'] == null ? undefined : json['channels'],
        'sampleRate': json['sample_rate'] == null ? undefined : json['sample_rate'],
    };
}

export function AudioMetadataToJSON(json: any): AudioMetadata {
    return AudioMetadataToJSONTyped(json, false);
}

export function AudioMetadataToJSONTyped(value?: AudioMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': DurationToJSON(value['duration']),
        'file_size_mb': value['fileSizeMb'],
        'codec': value['codec'],
        'channels': value['channels'],
        'sample_rate': value['sampleRate'],
    };
}

