/* tslint:disable */
/* eslint-disable */
/**
 * Griot and Grits API
 * Griot and Grits API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentInfo
 */
export interface ContentInfo {
    /**
     * 
     * @type {string}
     * @memberof ContentInfo
     */
    genre?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentInfo
     */
    language?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentInfo
     */
    themes?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentInfo
     */
    keywords?: Array<string>;
}

/**
 * Check if a given object implements the ContentInfo interface.
 */
export function instanceOfContentInfo(value: object): value is ContentInfo {
    return true;
}

export function ContentInfoFromJSON(json: any): ContentInfo {
    return ContentInfoFromJSONTyped(json, false);
}

export function ContentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'genre': json['genre'] == null ? undefined : json['genre'],
        'language': json['language'] == null ? undefined : json['language'],
        'themes': json['themes'] == null ? undefined : json['themes'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
    };
}

export function ContentInfoToJSON(json: any): ContentInfo {
    return ContentInfoToJSONTyped(json, false);
}

export function ContentInfoToJSONTyped(value?: ContentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'genre': value['genre'],
        'language': value['language'],
        'themes': value['themes'],
        'keywords': value['keywords'],
    };
}

