/* tslint:disable */
/* eslint-disable */
/**
 * Griot and Grits API
 * Griot and Grits API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Duration
 */
export interface Duration {
    /**
     * 
     * @type {number}
     * @memberof Duration
     */
    minutes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Duration
     */
    seconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Duration
     */
    hours?: number | null;
}

/**
 * Check if a given object implements the Duration interface.
 */
export function instanceOfDuration(value: object): value is Duration {
    return true;
}

export function DurationFromJSON(json: any): Duration {
    return DurationFromJSONTyped(json, false);
}

export function DurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Duration {
    if (json == null) {
        return json;
    }
    return {
        
        'minutes': json['minutes'] == null ? undefined : json['minutes'],
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
        'hours': json['hours'] == null ? undefined : json['hours'],
    };
}

export function DurationToJSON(json: any): Duration {
    return DurationToJSONTyped(json, false);
}

export function DurationToJSONTyped(value?: Duration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minutes': value['minutes'],
        'seconds': value['seconds'],
        'hours': value['hours'],
    };
}

