/* tslint:disable */
/* eslint-disable */
/**
 * Griot and Grits API
 * Griot and Grits API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Licensing
 */
export interface Licensing {
    /**
     * 
     * @type {string}
     * @memberof Licensing
     */
    licenseType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Licensing
     */
    licenseUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Licensing
     */
    rightsHolder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Licensing
     */
    expirationDate?: string | null;
}

/**
 * Check if a given object implements the Licensing interface.
 */
export function instanceOfLicensing(value: object): value is Licensing {
    return true;
}

export function LicensingFromJSON(json: any): Licensing {
    return LicensingFromJSONTyped(json, false);
}

export function LicensingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Licensing {
    if (json == null) {
        return json;
    }
    return {
        
        'licenseType': json['license_type'] == null ? undefined : json['license_type'],
        'licenseUrl': json['license_url'] == null ? undefined : json['license_url'],
        'rightsHolder': json['rights_holder'] == null ? undefined : json['rights_holder'],
        'expirationDate': json['expiration_date'] == null ? undefined : json['expiration_date'],
    };
}

export function LicensingToJSON(json: any): Licensing {
    return LicensingToJSONTyped(json, false);
}

export function LicensingToJSONTyped(value?: Licensing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'license_type': value['licenseType'],
        'license_url': value['licenseUrl'],
        'rights_holder': value['rightsHolder'],
        'expiration_date': value['expirationDate'],
    };
}

