/* tslint:disable */
/* eslint-disable */
/**
 * Griot and Grits API
 * Griot and Grits API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Duration } from './Duration';
import {
    DurationFromJSON,
    DurationFromJSONTyped,
    DurationToJSON,
    DurationToJSONTyped,
} from './Duration';
import type { AudioMetadata } from './AudioMetadata';
import {
    AudioMetadataFromJSON,
    AudioMetadataFromJSONTyped,
    AudioMetadataToJSON,
    AudioMetadataToJSONTyped,
} from './AudioMetadata';
import type { VideoMetadata } from './VideoMetadata';
import {
    VideoMetadataFromJSON,
    VideoMetadataFromJSONTyped,
    VideoMetadataToJSON,
    VideoMetadataToJSONTyped,
} from './VideoMetadata';

/**
 * 
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * 
     * @type {Duration}
     * @memberof Meta
     */
    duration?: Duration;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    fileSizeMb?: number;
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    codec?: string;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    channels?: number;
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    sampleRate?: string;
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    format?: string;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    resolutionHeight?: number;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    resolutionWidth?: number;
    /**
     * 
     * @type {number}
     * @memberof Meta
     */
    frameRate?: number;
}

/**
 * Check if a given object implements the Meta interface.
 */
export function instanceOfMeta(value: object): value is Meta {
    return true;
}

export function MetaFromJSON(json: any): Meta {
    return MetaFromJSONTyped(json, false);
}

export function MetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meta {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : DurationFromJSON(json['duration']),
        'fileSizeMb': json['file_size_mb'] == null ? undefined : json['file_size_mb'],
        'codec': json['codec'] == null ? undefined : json['codec'],
        'channels': json['channels'] == null ? undefined : json['channels'],
        'sampleRate': json['sample_rate'] == null ? undefined : json['sample_rate'],
        'format': json['format'] == null ? undefined : json['format'],
        'resolutionHeight': json['resolution_height'] == null ? undefined : json['resolution_height'],
        'resolutionWidth': json['resolution_width'] == null ? undefined : json['resolution_width'],
        'frameRate': json['frame_rate'] == null ? undefined : json['frame_rate'],
    };
}

export function MetaToJSON(json: any): Meta {
    return MetaToJSONTyped(json, false);
}

export function MetaToJSONTyped(value?: Meta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': DurationToJSON(value['duration']),
        'file_size_mb': value['fileSizeMb'],
        'codec': value['codec'],
        'channels': value['channels'],
        'sample_rate': value['sampleRate'],
        'format': value['format'],
        'resolution_height': value['resolutionHeight'],
        'resolution_width': value['resolutionWidth'],
        'frame_rate': value['frameRate'],
    };
}

